# Generated by Django 5.2.7 on 2025-10-14 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelefoneAdicional',
        ),
    ]
