# Generated by Django 5.2.7 on 2025-10-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0002_delete_telefoneadicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='telefone2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='rua',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='img_upload',
            field=models.ImageField(blank=True, null=True, upload_to='sobre/'),
        ),
    ]
