# Generated by Django 5.2.7 on 2025-10-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0003_contato_telefone2_endereco_bairro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='favicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon32', models.ImageField(blank=True, null=True, upload_to='favicon/')),
                ('favicon16', models.ImageField(blank=True, null=True, upload_to='favicon/')),
                ('favicon180', models.ImageField(blank=True, null=True, upload_to='favicon/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
            ],
        ),
    ]
