# Generated by Django 5.2.7 on 2025-10-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0004_favicon_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='favicon',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='favicon/'),
        ),
    ]
