# Generated by Django 5.2.7 on 2025-10-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0005_favicon_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redesocial',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
