# Generated by Django 5.2.7 on 2025-10-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0006_alter_redesocial_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redesocial',
            old_name='url',
            new_name='facebook',
        ),
        migrations.RemoveField(
            model_name='redesocial',
            name='nome',
        ),
        migrations.AddField(
            model_name='redesocial',
            name='instagram',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redesocial',
            name='x',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redesocial',
            name='youtube',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
