# Generated by Django 5.2.7 on 2025-10-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0007_rename_url_redesocial_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redesocial',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='redesocial',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='redesocial',
            name='x',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='redesocial',
            name='youtube',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
