# Generated by Django 5.2.7 on 2025-10-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0008_alter_redesocial_facebook_alter_redesocial_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_newletter', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_contato', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_duvidas', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_pos_venda', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_marketing', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_para_enviar_newletter', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_para_enviar_contato', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_para_enviar_duvidas', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_para_enviar_pos_venda', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_para_enviar_marketing', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
