# Generated by Django 5.2.7 on 2025-10-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0009_emails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emails',
            options={'verbose_name': 'Emails', 'verbose_name_plural': 'Emails'},
        ),
    ]
