# Generated by Django 5.2.7 on 2025-10-16 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0005_ano_carro_destaque_carro_promocao_and_more'),
        ('configuracao', '0010_alter_emails_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarroMaisVisualizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualizacoes', models.PositiveIntegerField(default=0)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencia.carro')),
            ],
            options={
                'verbose_name': 'Carro Mais Visualizados',
                'verbose_name_plural': 'Carros Mais Visualizados',
            },
        ),
    ]
