# Generated by Django 5.2.7 on 2025-10-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0011_carromaisvisualizados'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='foto_loja',
            field=models.ImageField(blank=True, null=True, upload_to='enderecos/'),
        ),
    ]
