# Generated by Django 5.2.7 on 2025-10-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0012_endereco_foto_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='nome_loja',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='foto_loja',
            field=models.ImageField(blank=True, null=True, upload_to='lojas_img/'),
        ),
    ]
