# Generated by Django 5.2.7 on 2025-10-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0002_carro_nome_carro_preco_carro_preco_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='cambio',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carro',
            name='combustivel',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carro',
            name='km',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carro',
            name='ano',
            field=models.CharField(max_length=100),
        ),
    ]
