# Generated by Django 5.2.7 on 2025-10-14 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0003_carro_cambio_carro_combustivel_carro_km_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carro',
            old_name='img_upload',
            new_name='imagem_principal',
        ),
        migrations.CreateModel(
            name='ImagemCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to='carros/galeria/')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='agencia.carro')),
            ],
        ),
    ]
