# Generated by Django 5.2.7 on 2025-10-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0004_rename_img_upload_carro_imagem_principal_imagemcarro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='carro',
            name='destaque',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='carro',
            name='promocao',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='img_upload',
            field=models.ImageField(blank=True, null=True, upload_to='marcas/'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='img_upload',
            field=models.ImageField(blank=True, null=True, upload_to='modelos/'),
        ),
    ]
