# Generated by Django 5.2.7 on 2025-10-16 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0005_ano_carro_destaque_carro_promocao_and_more'),
        ('mensagens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoDeProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencia.carro')),
            ],
            options={
                'verbose_name': 'Solicitação de Proposta',
                'verbose_name_plural': 'Solicitações de Propostas',
            },
        ),
    ]
