# Generated by Django 5.2.7 on 2025-10-16 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0013_endereco_nome_loja_alter_endereco_foto_loja'),
        ('mensagens', '0002_solicitacaodeproposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='posvendas',
            name='loja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracao.endereco'),
            preserve_default=False,
        ),
    ]
