# Generated by Django 5.2.7 on 2025-10-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0003_posvendas_loja'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posvendas',
            options={'verbose_name': 'Pos Venda', 'verbose_name_plural': 'Pos Vendas'},
        ),
        migrations.RemoveField(
            model_name='posvendas',
            name='financiamento',
        ),
        migrations.AlterField(
            model_name='posvendas',
            name='como_nos_conheceu',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
