# Generated by Django 5.2.7 on 2025-10-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0004_alter_posvendas_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaFinanciamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('cnh', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNH')),
                ('telefone', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('estado_civil', models.CharField(choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)')], max_length=15)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('marca_veiculo', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo_veiculo', models.CharField(blank=True, max_length=100, null=True)),
                ('ano_fabricacao', models.CharField(blank=True, max_length=10, null=True)),
                ('valor_entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Entrada')),
                ('valor_a_financiar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor a Financiar')),
                ('qtd_parcelas', models.IntegerField(choices=[(12, '12x'), (24, '24x'), (36, '36x'), (48, '48x'), (60, '60x')], verbose_name='Quantidade de Parcelas')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=20, verbose_name='Status da Solicitação')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
            ],
            options={
                'verbose_name': 'Ficha de Financiamento',
                'verbose_name_plural': 'Fichas de Financiamento',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
