# Generated by Django 5.2.7 on 2025-10-16 18:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0005_fichafinanciamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropostaVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('versao', models.CharField(max_length=100)),
                ('quilometragem', models.PositiveIntegerField(verbose_name='Quilometragem (KM)')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano do Veículo')),
                ('valor_desejado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nome_proprietario', models.CharField(max_length=255)),
                ('email_proprietario', models.EmailField(max_length=254)),
                ('telefone_proprietario', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('contatado', 'Contatado'), ('recusado', 'Recusado')], default='pendente', max_length=20)),
                ('data_proposta', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Proposta de Venda',
                'verbose_name_plural': 'Propostas de Venda',
                'ordering': ['-data_proposta'],
            },
        ),
        migrations.CreateModel(
            name='FotoPropostaVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='propostas_venda/')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='mensagens.propostavenda')),
            ],
        ),
    ]
